version: '3.8'

services:
  # ChoreMe application with SQLite (default, simplest setup)
  choreme:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=sqlite
      - DB_NAME=/data/choreme.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - GIN_MODE=release
    volumes:
      - choreme_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alternative: ChoreMe with PostgreSQL
  choreme-postgres:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=choreme
      - DB_USER=choreme
      - DB_PASS=password
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: choreme
      POSTGRES_USER: choreme
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U choreme"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

  # Alternative: ChoreMe with MySQL
  choreme-mysql:
    build: .
    ports:
      - "8082:8080"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=choreme
      - DB_USER=choreme
      - DB_PASS=password
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - GIN_MODE=release
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: choreme
      MYSQL_USER: choreme
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "choreme", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - mysql

  # Reverse proxy (optional)
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    profiles:
      - proxy

volumes:
  choreme_data:
  postgres_data:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: choreme-network