import { Container, ContainerProps, Stack, Typography } from "@mui/material";
import React, { ReactNode } from "react";
import LoadingOverlay from "react-loading-overlay";
import { ChoreMeAvatar } from "../avatar";
import { DropDownMenu } from "../menu";
import { ChoreMeBreadcrumbs } from "../breadcrumbs";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

export type ChoreLayoutProps = ContainerProps & {
  title?: string;
  avatar?: ReactNode;
  isLoading?: boolean;
};

export const ChoreLayout: React.FC<ChoreLayoutProps> = ({
  title,
  avatar,
  isLoading,
  children,
  ...props
}) => {
  const [showMenu, setShowMenu] = React.useState(false);
  return (
    <main>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LoadingOverlay active={isLoading} spinner>
        <Container
          sx={{
            paddingTop: "1rem",
          }}
        >
          <Stack
            direction={"row"}
            justifyContent={"space-between"}
            onMouseEnter={() => setShowMenu(true)}
            onMouseLeave={() =>
              setTimeout(() => {
                setShowMenu(false);
              }, 1000)
            }
          >
            <Typography variant={"h4"}>{title}</Typography>
            {avatar}
            {showMenu && (
              <DropDownMenu
                sx={{
                  position: "absolute",
                  top: 0,
                  right: 0,
                  bgcolor: "background.paper",
                }}
              />
            )}
          </Stack>
          <ChoreMeBreadcrumbs />
          {children}
        </Container>
      </LoadingOverlay>
    </main>
  );
};

ChoreLayout.defaultProps = {
  title: "Chore Me",
  avatar: <ChoreMeAvatar />,
};
