import {
  Card,
  CardContent,
  Typography,
  CardActions,
  Button,
} from "@mui/material";
import { styled } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import Container from "../../components/layout/Container";
import styles from "../../styles/Home.module.css";

const StyledButtonDiv = styled("div")`
  display: flex;
  flex-direction: row;
  justify-content: center;
`;
const StyledTextInputDiv = styled("div")`
  display: flex;
  flex-direction: column;
`;
const StyledLogoDiv = styled("div")`
  display: flex;
  justify-content: center;
`;

const MainStyled = styled("div")`
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
`;

const Error: NextPage = () => {
  const { query, push } = useRouter();
  const [state, setState] = useState({ email: "", password: "" });

  const onTextChanged = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.target.name === "email";
    switch (e.target.name) {
      case "email":
        setState({ ...state, email: e.target.value });
        break;
      case "password":
        setState({ ...state, password: e.target.value });
        break;
      default:
        break;
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Chore Me - Error</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Card sx={{ minWidth: 275 }}>
          <CardContent>
            <Typography
              sx={{ fontSize: 14 }}
              color="text.secondary"
              gutterBottom
            >
              Authentication Error
            </Typography>
            <Typography variant="h5" component="div">
              {query.error}
            </Typography>
          </CardContent>
          <CardActions>
            <Button size="small" onClick={() => push("/auth")}>
              OK
            </Button>
          </CardActions>
        </Card>
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Error;
