import { Typography } from "@mui/material";
import { styled } from "@mui/system";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import NormalButton from "../../components/button/NormalButton";
import Container from "../../components/layout/Container";
import NormalTextInput from "../../components/text-input/normal-text-input";
import styles from "../../styles/Home.module.css";

const StyledButtonDiv = styled("div")`
  display: flex;
  flex-direction: row;
  justify-content: center;
`;
const StyledTextInputDiv = styled("div")`
  display: flex;
  flex-direction: column;
`;
const StyledLogoDiv = styled("div")`
  display: flex;
  justify-content: center;
`;

const MainStyled = styled("div")`
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
  max-width: 500px;
`;

const Auth: NextPage = () => {
  const router = useRouter();
  const [state, setState] = useState({ email: "", password: "" });

  const onTextChanged = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.target.name === "email";
    switch (e.target.name) {
      case "email":
        setState({ ...state, email: e.target.value });
        break;
      case "password":
        setState({ ...state, password: e.target.value });
        break;
      default:
        break;
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Chore Me - Authentication</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <MainStyled>
          <StyledLogoDiv>
            <img
              src="/images/logo.png"
              alt="logo"
              height="110px"
              width={"110px"}
            />
          </StyledLogoDiv>
          <StyledTextInputDiv>
            <NormalTextInput
              label="Email"
              color="primary"
              name="email"
              type="email"
              onChange={onTextChanged}
            />
            <NormalTextInput
              label="Password"
              color="primary"
              name="password"
              type="password"
              onChange={onTextChanged}
            />
          </StyledTextInputDiv>
          <StyledButtonDiv>
            <NormalButton
              variant="contained"
              color="primary"
              onClick={() =>
                signIn("credentials", {
                  email: state.email,
                  password: state.password,
                  callbackUrl: "/",
                })
              }
            >
              <Typography variant="button">Sign In</Typography>
            </NormalButton>
            <NormalButton
              variant="contained"
              color="primary"
              onClick={() => router.push("/auth/signup")}
            >
              <Typography variant="button">Sign Up</Typography>
            </NormalButton>
          </StyledButtonDiv>
        </MainStyled>
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Auth;
